spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@112.74.45.31:1521:orcl
    username: sccs
    password: sccs1234

mybatis:
  type-aliases-package: cn.edu.guet.model
  mapper-locations: classpath:mapper/*.xml
server:
  servlet:
    context-path: /SCCSBackEnd
  port: 8080
logging:
  level:
    root: INFO
    cn.edu.guet.mapper: DEBUG